### ISSUE TITLE
json-spec-openapi-0.3.1.0 not compatible with lens-5.3

### ISSUE THREAD

**Issue by ysangkok** [owensmurray/json-spec-openapi#10]
Compatibility with this new release of lens is required for GHC 9.10 support. See

* https://github.com/commercialhaskell/stackage/issues/7408

BTW you can now get notifications on Hackage when you don't accept new versions of dependencies, see [discourse](https://discourse.haskell.org/t/hackage-dep-bound-notifications-and-uploader-endorsements-for-new-users/8342?u=janus)

**Comment by rickowens** [comment]
Thanks for the ping! I plan to get to this early this week (just didn't quite make it last week when I did a lot of similar updates).

**Comment by ysangkok** [comment]
No problem, there really isn't any rush. I am just pinging because lens-5.3 has been out for a couple of months now. So there are just a few packages left.  It would be nice to not have to churn through the removal/addition process when Stackage Nightly upgrades.

**Comment by rickowens** [comment]
https://hackage.haskell.org/package/json-spec-openapi-0.3.1.1

**Comment by ysangkok** [comment]
Seems to work, thank you!
